from haiku_baselines.DQN.dqn import DQN
from haiku_baselines.C51.c51 import C51
from haiku_baselines.QRDQN.qrdqn import QRDQN
from haiku_baselines.IQN.iqn import IQN
from haiku_baselines.FQF.fqf import FQF
from haiku_baselines.DDPG.ddpg import DDPG
from haiku_baselines.TD3.td3 import TD3
from haiku_baselines.TQC.tqc import TQC
from haiku_baselines.TQC_IQN.tqc_iqn import TQC_IQN
from haiku_baselines.A2C.a2c import A2C
from haiku_baselines.PPO.ppo import PPO
from haiku_baselines.TPPO.tppo import TPPO