from jax_baselines.A2C.a2c import A2C
from jax_baselines.C51.c51 import C51
from jax_baselines.DDPG.ddpg import DDPG
from jax_baselines.DQN.dqn import DQN
from jax_baselines.FQF.fqf import FQF
from jax_baselines.IQN.iqn import IQN
from jax_baselines.PPO.ppo import PPO
from jax_baselines.QRDQN.qrdqn import QRDQN
from jax_baselines.TD3.td3 import TD3
from jax_baselines.TPPO.tppo import TPPO
from jax_baselines.TQC.tqc import TQC
